repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: Ruff linter
        entry: ruff check .
        language: python
        types: [python]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Mypy type checker
        language: python
        types: [python]
        pass_filenames: false
        args: [eval_crypt]
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false 